# Generated by Django 4.1.7 on 2023-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First Name')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('MobileNumber', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('Gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('Email', models.CharField(max_length=50, verbose_name='Email Id')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('password', models.CharField(max_length=50, verbose_name='Enter Password')),
            ],
        ),
    ]
